"""baseline evidence store

Revision ID: b6391cb56188
Revises:
Create Date: 2026-08-05 18:13:18.077023
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "b6391cb56188"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "repository",
        sa.Column("id", sa.String(length=200), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("remote_url", sa.Text(), nullable=True),
        sa.Column("default_branch", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repository")),
    )
    op.create_table(
        "revision",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repository_id", sa.String(length=200), nullable=False),
        sa.Column("sha", sa.String(length=40), nullable=False),
        sa.Column("ref_name", sa.String(length=300), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"], ["repository.id"], name=op.f("fk_revision_repository_id_repository")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_revision")),
        sa.UniqueConstraint("repository_id", "sha", name=op.f("uq_revision_repository_id")),
    )
    op.create_table(
        "file",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("revision_id", sa.Integer(), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("git_blob_sha", sa.String(length=40), nullable=False),
        sa.Column("language", sa.String(length=40), nullable=True),
        sa.Column("is_generated", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["revision_id"], ["revision.id"], name=op.f("fk_file_revision_id_revision")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_file")),
        sa.UniqueConstraint("revision_id", "path", name=op.f("uq_file_revision_id")),
    )
    op.create_table(
        "run",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("repository_id", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("pr_number", sa.Integer(), nullable=True),
        sa.Column("base_revision_id", sa.Integer(), nullable=True),
        sa.Column("head_revision_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("pipeline_version", sa.String(length=60), nullable=True),
        sa.Column("skill_registry_sha256", sa.String(length=71), nullable=True),
        sa.Column("config_sha256", sa.String(length=71), nullable=True),
        sa.Column("toolchain", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("cost", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("manifest_sha256", sa.String(length=71), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('created','running','paused_for_approval','succeeded','succeeded_with_gaps','failed','cancelled')",
            name=op.f("ck_run_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["base_revision_id"], ["revision.id"], name=op.f("fk_run_base_revision_id_revision")
        ),
        sa.ForeignKeyConstraint(
            ["head_revision_id"], ["revision.id"], name=op.f("fk_run_head_revision_id_revision")
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"], ["repository.id"], name=op.f("fk_run_repository_id_repository")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run")),
    )
    op.create_table(
        "agent_invocation",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("run_id", sa.String(length=26), nullable=False),
        sa.Column("task_id", sa.String(length=26), nullable=False),
        sa.Column("skill_id", sa.String(length=60), nullable=False),
        sa.Column("skill_version", sa.String(length=30), nullable=False),
        sa.Column("engine", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("transcript_sha256", sa.String(length=71), nullable=True),
        sa.Column("result_sha256", sa.String(length=71), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["run.id"], name=op.f("fk_agent_invocation_run_id_run")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_invocation")),
        sa.UniqueConstraint("task_id", name=op.f("uq_agent_invocation_task_id")),
    )
    op.create_index(
        op.f("ix_agent_invocation_run_id"), "agent_invocation", ["run_id"], unique=False
    )
    op.create_table(
        "artifact",
        sa.Column("sha256", sa.String(length=71), nullable=False),
        sa.Column("kind", sa.String(length=60), nullable=False),
        sa.Column("media_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("schema_id", sa.String(length=60), nullable=True),
        sa.Column("producer", sa.String(length=100), nullable=False),
        sa.Column("produced_by_run_id", sa.String(length=26), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["produced_by_run_id"], ["run.id"], name=op.f("fk_artifact_produced_by_run_id_run")
        ),
        sa.PrimaryKeyConstraint("sha256", name=op.f("pk_artifact")),
    )
    op.create_table(
        "extractor_receipt",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("run_id", sa.String(length=26), nullable=False),
        sa.Column("extractor", sa.String(length=60), nullable=False),
        sa.Column("extractor_version", sa.String(length=200), nullable=False),
        sa.Column("revision_sha", sa.String(length=40), nullable=False),
        sa.Column("exit_code", sa.Integer(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["run.id"], name=op.f("fk_extractor_receipt_run_id_run")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_extractor_receipt")),
    )
    op.create_index(
        op.f("ix_extractor_receipt_run_id"), "extractor_receipt", ["run_id"], unique=False
    )
    op.create_table(
        "finding",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("run_id", sa.String(length=26), nullable=False),
        sa.Column("finding_id", sa.String(length=10), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("claim", sa.Text(), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("start_line", sa.Integer(), nullable=True),
        sa.Column("end_line", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("duplicate_of", sa.String(length=10), nullable=True),
        sa.Column("discovered_by_skill", sa.String(length=60), nullable=False),
        sa.Column("skill_version", sa.String(length=30), nullable=False),
        sa.Column("introduced_by_change", sa.Boolean(), nullable=True),
        sa.Column("publication_eligible", sa.Boolean(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("validation", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "status IN ('candidate','validated','rejected','duplicate','unresolved','suppressed')",
            name=op.f("ck_finding_status_valid"),
        ),
        sa.ForeignKeyConstraint(["run_id"], ["run.id"], name=op.f("fk_finding_run_id_run")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_finding")),
        sa.UniqueConstraint("run_id", "finding_id", name=op.f("uq_finding_run_id")),
    )
    op.create_index(op.f("ix_finding_run_id"), "finding", ["run_id"], unique=False)
    op.create_table(
        "run_event",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("run_id", sa.String(length=26), nullable=False),
        sa.Column("stage", sa.String(length=60), nullable=False),
        sa.Column("event", sa.String(length=60), nullable=False),
        sa.Column("level", sa.String(length=10), nullable=False),
        sa.Column(
            "at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(["run_id"], ["run.id"], name=op.f("fk_run_event_run_id_run")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_event")),
    )
    op.create_index(op.f("ix_run_event_run_id"), "run_event", ["run_id"], unique=False)
    op.create_table(
        "approval",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.String(length=26), nullable=False),
        sa.Column("action_kind", sa.String(length=40), nullable=False),
        sa.Column("payload_sha256", sa.String(length=71), nullable=False),
        sa.Column(
            "requested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_by", sa.String(length=100), nullable=True),
        sa.Column("decision", sa.String(length=10), nullable=True),
        sa.Column("decision_note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["payload_sha256"],
            ["artifact.sha256"],
            name=op.f("fk_approval_payload_sha256_artifact"),
        ),
        sa.ForeignKeyConstraint(["run_id"], ["run.id"], name=op.f("fk_approval_run_id_run")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approval")),
    )
    op.create_index(op.f("ix_approval_run_id"), "approval", ["run_id"], unique=False)
    op.create_table(
        "graph_snapshot",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.String(length=26), nullable=False),
        sa.Column("revision_id", sa.Integer(), nullable=False),
        sa.Column("schema_version", sa.String(length=20), nullable=False),
        sa.Column("canonical_sha256", sa.String(length=71), nullable=False),
        sa.Column("artifact_sha256", sa.String(length=71), nullable=False),
        sa.Column("node_count", sa.Integer(), nullable=False),
        sa.Column("edge_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["artifact_sha256"],
            ["artifact.sha256"],
            name=op.f("fk_graph_snapshot_artifact_sha256_artifact"),
        ),
        sa.ForeignKeyConstraint(
            ["revision_id"], ["revision.id"], name=op.f("fk_graph_snapshot_revision_id_revision")
        ),
        sa.ForeignKeyConstraint(["run_id"], ["run.id"], name=op.f("fk_graph_snapshot_run_id_run")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_graph_snapshot")),
    )
    op.create_index(op.f("ix_graph_snapshot_run_id"), "graph_snapshot", ["run_id"], unique=False)
    op.create_table(
        "graph_edge",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("snapshot_id", sa.Integer(), nullable=False),
        sa.Column("natural_id", sa.Text(), nullable=False),
        sa.Column("source_natural_id", sa.Text(), nullable=False),
        sa.Column("target_natural_id", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("configuration", sa.Text(), nullable=True),
        sa.Column("attrs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["graph_snapshot.id"],
            name=op.f("fk_graph_edge_snapshot_id_graph_snapshot"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_graph_edge")),
        sa.UniqueConstraint("snapshot_id", "natural_id", name=op.f("uq_graph_edge_snapshot_id")),
    )
    op.create_index(op.f("ix_graph_edge_snapshot_id"), "graph_edge", ["snapshot_id"], unique=False)
    op.create_index(
        op.f("ix_graph_edge_source_natural_id"), "graph_edge", ["source_natural_id"], unique=False
    )
    op.create_index(
        op.f("ix_graph_edge_target_natural_id"), "graph_edge", ["target_natural_id"], unique=False
    )
    op.create_table(
        "graph_node",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("snapshot_id", sa.Integer(), nullable=False),
        sa.Column("natural_id", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("path", sa.Text(), nullable=True),
        sa.Column("start_line", sa.Integer(), nullable=True),
        sa.Column("end_line", sa.Integer(), nullable=True),
        sa.Column("attrs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["graph_snapshot.id"],
            name=op.f("fk_graph_node_snapshot_id_graph_snapshot"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_graph_node")),
        sa.UniqueConstraint("snapshot_id", "natural_id", name=op.f("uq_graph_node_snapshot_id")),
    )
    op.create_index(op.f("ix_graph_node_snapshot_id"), "graph_node", ["snapshot_id"], unique=False)
    op.create_table(
        "publication",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("approval_id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.String(length=26), nullable=False),
        sa.Column("target_kind", sa.String(length=40), nullable=False),
        sa.Column("external_ref", sa.Text(), nullable=True),
        sa.Column("payload_sha256", sa.String(length=71), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["approval_id"], ["approval.id"], name=op.f("fk_publication_approval_id_approval")
        ),
        sa.ForeignKeyConstraint(["run_id"], ["run.id"], name=op.f("fk_publication_run_id_run")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_publication")),
    )
    op.create_index(op.f("ix_publication_run_id"), "publication", ["run_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_publication_run_id"), table_name="publication")
    op.drop_table("publication")
    op.drop_index(op.f("ix_graph_node_snapshot_id"), table_name="graph_node")
    op.drop_table("graph_node")
    op.drop_index(op.f("ix_graph_edge_target_natural_id"), table_name="graph_edge")
    op.drop_index(op.f("ix_graph_edge_source_natural_id"), table_name="graph_edge")
    op.drop_index(op.f("ix_graph_edge_snapshot_id"), table_name="graph_edge")
    op.drop_table("graph_edge")
    op.drop_index(op.f("ix_graph_snapshot_run_id"), table_name="graph_snapshot")
    op.drop_table("graph_snapshot")
    op.drop_index(op.f("ix_approval_run_id"), table_name="approval")
    op.drop_table("approval")
    op.drop_index(op.f("ix_run_event_run_id"), table_name="run_event")
    op.drop_table("run_event")
    op.drop_index(op.f("ix_finding_run_id"), table_name="finding")
    op.drop_table("finding")
    op.drop_index(op.f("ix_extractor_receipt_run_id"), table_name="extractor_receipt")
    op.drop_table("extractor_receipt")
    op.drop_table("artifact")
    op.drop_index(op.f("ix_agent_invocation_run_id"), table_name="agent_invocation")
    op.drop_table("agent_invocation")
    op.drop_table("run")
    op.drop_table("file")
    op.drop_table("revision")
    op.drop_table("repository")
    # ### end Alembic commands ###
