"""run_artifact membership

Revision ID: bf0c6e3f1cc1
Revises: b6391cb56188
Create Date: 2026-08-06 00:55:44.408346
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "bf0c6e3f1cc1"
down_revision = "b6391cb56188"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "run_artifact",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("run_id", sa.String(length=26), nullable=False),
        sa.Column("sha256", sa.String(length=71), nullable=False),
        sa.Column("role", sa.String(length=60), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["run_id"], ["run.id"], name=op.f("fk_run_artifact_run_id_run")),
        sa.ForeignKeyConstraint(
            ["sha256"], ["artifact.sha256"], name=op.f("fk_run_artifact_sha256_artifact")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_artifact")),
        sa.UniqueConstraint("run_id", "sha256", "role", name=op.f("uq_run_artifact_run_id")),
    )
    op.create_index(op.f("ix_run_artifact_run_id"), "run_artifact", ["run_id"], unique=False)
    op.create_index(op.f("ix_run_artifact_sha256"), "run_artifact", ["sha256"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_run_artifact_sha256"), table_name="run_artifact")
    op.drop_index(op.f("ix_run_artifact_run_id"), table_name="run_artifact")
    op.drop_table("run_artifact")
    # ### end Alembic commands ###
