"""Regenerate .agents/skills/registry.yaml with current skill content hashes.

Run after deliberately changing a skill — and bump that skill's version here so
its replay cassettes are invalidated rather than silently reused (ADR-0008,
ADR-0012). The registry is data the loader verifies; regenerating it is an
explicit act, which is why it is a script and not an import-time side effect.

Usage: uv run python scripts/update_registry.py
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
SKILLS_ROOT = REPO_ROOT / ".agents" / "skills"

REVIEWER = "findings.v1"

SKILLS: list[dict[str, Any]] = [
    {
        "id": "echo-skill",
        "version": "1.0.0",
        "purpose": "Adapter validation: count Rust files and echo the revision",
        "output_schema": "echo-result.v1",
        "commands": ["rg --files"],
    },
    {
        "id": "intent-reconstructor",
        "version": "1.0.0",
        "purpose": "Reconstruct stated intent from specs, ADRs and repository rules",
        "output_schema": "intent.v1",
        "commands": [],
    },
    {
        "id": "reviewer-correctness",
        # 1.2.0: threatFocus input aims and calibrates; 1.1.0 was the certainty bar.
        "version": "1.2.0",
        "purpose": "Correctness review: wrong results, reachable panics, broken invariants, races",
        "output_schema": REVIEWER,
        "commands": [],
    },
    {
        "id": "reviewer-security",
        # 1.2.0: threatFocus input aims and calibrates; 1.1.0 was the certainty bar.
        "version": "1.2.0",
        "purpose": "Security review: attacker-reachable capabilities and broken controls",
        "output_schema": REVIEWER,
        "commands": [],
    },
    {
        "id": "reviewer-architecture",
        # 1.2.0: threatFocus input aims and calibrates; 1.1.0 was the certainty bar.
        "version": "1.2.0",
        "purpose": "Architecture review: contradictions with accepted decisions and boundaries",
        "output_schema": REVIEWER,
        "commands": [],
    },
    {
        "id": "finding-validator",
        # 1.1.0: `reason` is required and feeds cross-run memory.
        "version": "1.1.0",
        "purpose": "Adversarially validate one candidate finding in a fresh context",
        "output_schema": "validation-result.v1",
        "commands": ["cargo test", "rg"],
    },
    {
        "id": "change-explainer",
        "version": "1.0.0",
        "purpose": "Explain what a change did: before, after, structure, impact, risks",
        "output_schema": "change-explanation.v1",
        "commands": [],
    },
    {
        "id": "project-explainer",
        "version": "1.0.0",
        "purpose": "Explain what a project is and how to find your way around it",
        "output_schema": "project-explanation.v1",
        "commands": [],
    },
    {
        "id": "code-answerer",
        "version": "1.0.0",
        "purpose": "Answer one question about one module or symbol, cited or refused",
        "output_schema": "code-answer.v1",
        "commands": [],
    },
    {
        "id": "protocol-modeler",
        "version": "1.0.0",
        "purpose": "Model the protocol a project speaks, or state that it speaks none",
        "output_schema": "protocol-model.v1",
        "commands": [],
    },
    {
        "id": "threat-modeler",
        "version": "1.0.0",
        "purpose": "Model a repository's trust boundaries and abuse paths, or say it has none",
        "output_schema": "threat-model.v1",
        "commands": [],
    },
    {
        "id": "attack-path-analyst",
        "version": "1.0.0",
        "purpose": "Trace the attack path behind a validated security finding, gaps admitted",
        "output_schema": "attack-path.v1",
        "commands": ["rg"],
    },
]

HEADER = """# Trusted skill registry (ADR-0008). GENERATED by scripts/update_registry.py.
#
# Every skill is pinned by content hash: the loader recomputes the hash over all
# files in the skill directory and refuses to run on mismatch. Regenerate hashes
# deliberately when changing a skill, and bump its version so cassettes invalidate.

skills:"""


def main() -> int:
    from codeatlas.agents.registry import compute_skill_hash

    lines = [HEADER]
    for skill in SKILLS:
        skill_dir = SKILLS_ROOT / str(skill["id"])
        if not skill_dir.is_dir():
            print(f"missing skill directory: {skill_dir}")
            return 1
        sha = compute_skill_hash(skill_dir)
        commands = ", ".join(f'"{c}"' for c in skill["commands"])
        lines += [
            f"  - id: {skill['id']}",
            f'    version: "{skill["version"]}"',
            f"    path: {skill['id']}/",
            f'    content_sha256: "{sha}"',
            f'    purpose: "{skill["purpose"]}"',
            f"    output_schema: {skill['output_schema']}",
            "    permissions:",
            f"      commands: [{commands}]",
            "      network: false",
            "      writes: []",
            "    trust: trusted",
            '    reviewed_by: "xaga.ogay@gmail.com"',
            '    reviewed_at: "2026-08-05"',
        ]
        print(f"{skill['id']:<24} {sha}")

    (SKILLS_ROOT / "registry.yaml").write_text(
        "\n".join(lines) + "\n", encoding="utf-8", newline="\n"
    )
    print(f"\nwrote {SKILLS_ROOT / 'registry.yaml'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
